### ISSUE TITLE
model.$get($self) returns hasManys

### ISSUE THREAD

**Issue by mrpinsky** [kstf/plump#20]
In test suite, calling testType.$get($self) returns an object that includes (empty) fields for agreers, agreees, likers, likees, parents, children, queryChildren, queryParents, valenceChildren, and valenceParents

**Comment by ericeslinger** [comment]
$get($self) should only return the self fields, none of the un-fetched child fields. This happens because deep down $get resolves to a copy of the object store, a filter needs to get put on to prevent this.
