### ISSUE TITLE
Cacheable Writes are not propagating to instantiated models

### ISSUE THREAD

**Issue by ericeslinger** [kstf/plump#30]
Repro is in [this test](https://github.com/kstf/plump/blob/master/src/test/model.spec.js#L161).

Basically:

- create a model, save it.
- create a second model pointing to the original data (like `plump.find('tests', 1)` if the first one was $id = 1
- update the first model.
- do a $get on the second model. 

Expected: the first model should look like the second (they should both update on a $save().
Actual: that doesn't happen.

**Comment by ericeslinger** [comment]
There's no good solution to this problem that preserves the Model object's `Model[$store]` cache layer. If we want to invalidate the cache, we have to listen to plump for update events, and if we're doing that, we are generating a listener on plump with a reference to our model.

That would lead to a resource leak, since we would have to explicitly deconstruct any model object that's ever created (the models would be reachable from plump, so wouldn't get garbage collected when their creating scope is destroyed, as I understand how JavasScript GC works - I might be wrong about that though). There's no percentage in that - as it is, we have to teardown models we do a subscribe on, but that at least makes sense (and is more rare).

This *also* feels like a shoehorning in anyway - we want to cache the results from store.read in the model so we don't have to keep hitting the store for contents already fetched. In a model lifecycle, I imagine this will be rare anyway (use case: create model, do something to it in a REST controller, dispose of model; on the front-end a long-lifecycle model is `subscribe()`d anyway.

So I propose to take off the $store on the model and always respond to $gets by doing a store.read. If the end user wants to have these things be cached, put a hot cache in the plump stack, that's what hot caches are for - in-memory. The difference is that there's only one listener, between the memstore and plump, and while the memstore grows in the number of things fetched, it can implement a LRU process to expire stuff pretty easily, and we're not growing in number of things fetched X number of times they were fetched.

**Comment by ericeslinger** [comment]
@mrpinsky see above

**Comment by mrpinsky** [comment]
I think pushing cached data to an explicit hot cache instead of trying to maintain a model $store makes sense.

**Comment by ericeslinger** [comment]
this is proving a bit problematic - there's a couple times when we really do want a $store (basically when there's local unsaved data). It also makes doing a $get when there's no plump attached also problematic.

This difficulty is mostly null guards and so on, but I'm making progress.

**Comment by ericeslinger** [comment]
This is a huge rewrite we're in the middle of right now - we're pulling $store off of the model

**Comment by ericeslinger** [comment]
Closed in #53
